# Generated by Django 4.1.7 on 2023-03-18 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='fecha_nacimiento',
            new_name='reserva',
        ),
        migrations.RenameField(
            model_name='reservas',
            old_name='numero_reserva',
            new_name='reserva',
        ),
        migrations.AlterField(
            model_name='reservas',
            name='fecha',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='reservas',
            name='horario',
            field=models.TimeField(),
        ),
    ]
